#!/usr/bin/php
<?php

require("a2.php");

// PROGRAM BODY BEGINS

$usage = "Usage: $argv[0] Name M N";
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 4 or count($argv) > 4) exit("$usage\n");

// firstly, we need get the actor
$name = $argv[1];
$start = $argv[2];
$end = $argv[3];

if ($start < 1 or $end > 6 or $start > $end) exit("$usage\n");

$get_actor_id = <<<ACTORID
    SELECT id FROM actor where lower(name) = lower(%s);
ACTORID;

$actor_id = dbNext(dbQuery($db, mkSQL($get_actor_id, $name)));

$query = <<<QUERY
  DROP INDEX IF EXISTS ac;
  CREATE INDEX ac ON acting(actor_id, movie_id);
  DROP INDEX IF EXISTS a;
  CREATE INDEX a ON actor(id);


  CREATE OR REPLACE FUNCTION find_degree(start_value INTEGER, end_value INTEGER, start_actors INT[], all_actors INT[])
    RETURNS TABLE (ds INTEGER, ac INT[]) AS $$
  DECLARE
    newactors INT[];
  BEGIN 

    SELECT array_agg(DISTINCT actor_id) INTO newactors FROM acting ac
    WHERE EXISTS (SELECT DISTINCT movie_id FROM acting WHERE (actor_id = any(start_actors)) AND ac.movie_id = movie_id)
          AND NOT (actor_id = any(all_actors));

    RETURN QUERY SELECT start_value, newactors;

    IF start_value < end_value THEN 
      RETURN QUERY SELECT * FROM find_degree(start_value + 1, end_value, newactors, array_cat(all_actors, newactors)::INT[]);
    END IF ;
  END ;
  $$ LANGUAGE plpgsql;
  
  CREATE OR REPLACE VIEW get_actors as
    SELECT * FROM find_degree(1,%d,ARRAY [%d]::INT[],ARRAY [%d]::INT[]);

QUERY;

dbQuery($db, mkSQL($query, $end, $actor_id[0], $actor_id[0]));

$index = 1;
for ($i = $start; $i <= $end; $i++) {
    $get_actors = <<<GETACTORS
    SELECT name 
    FROM actor 
    WHERE id IN 
      (SELECT unnest(ac) 
              FROM get_actors 
              WHERE ds = %d) 
    ORDER BY lower(name) ASC;
GETACTORS;
    $res = dbQuery($db, mkSQL($get_actors, $i));
    $index = show_actors($index, $i, $res);
}

// Iterate through the results and print
function show_actors($index,$ds, $res) {

    while ($tuple = dbNext($res)) {

        echo "$index. $tuple[0] ($ds)\n";
        $index ++;
    }

    return $index;
}

$query = <<<DROPSTUFF
    DROP INDEX ac;
    DROP INDEX a;
    DROP VIEW get_actors;
    DROP FUNCTION find_degree(start_value INTEGER, end_value INTEGER, start_actors INT[], all_actors INT[]);
    
DROPSTUFF;

dbQuery($db, mkSQL($query));


?>
