#!/usr/bin/php
<?php

error_reporting( E_ALL&~E_NOTICE );
require("a2.php");

// PROGRAM BODY BEGINS

$usage = "Usage: $argv[0] Actor Actor";
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 2 or count($argv) > 3) exit("$usage\n");

// firstly, we need get the actor
$first_actor = $argv[1];
$second_actor = $argv[2];

$get_actor_id = <<<ACTORID
    SELECT id FROM actor where lower(name) = lower(%s);
ACTORID;

$actor1 = dbNext(dbQuery($db, mkSQL($get_actor_id, $first_actor)));
$actor2 = dbNext(dbQuery($db, mkSQL($get_actor_id, $second_actor)));



$query = <<<QUERY
    DROP INDEX IF EXISTS ac;
    CREATE INDEX ac ON acting(actor_id, movie_id);
    DROP INDEX IF EXISTS a;
    CREATE INDEX a ON actor(id);  
    
    CREATE OR REPLACE FUNCTION find_degree(start_value INTEGER, end_value INTEGER, start_actors INT[], all_actors INT[])
        RETURNS TABLE (ds INTEGER, ac INT[]) AS $$
        DECLARE
            newactors INT[];
        BEGIN 
        
            SELECT array_agg(DISTINCT actor_id) INTO newactors FROM acting ac
            WHERE EXISTS (SELECT DISTINCT movie_id FROM acting WHERE (actor_id = any(start_actors)) AND ac.movie_id = movie_id)
                  AND NOT (actor_id = any(all_actors));
            
            RETURN QUERY SELECT start_value, newactors;
            
            IF start_value < end_value THEN 
              RETURN QUERY SELECT * FROM find_degree(start_value + 1, end_value, newactors, array_cat(all_actors, newactors)::INT[]);
            END IF ;
        END ;
        $$ LANGUAGE plpgsql;
        
    CREATE OR REPLACE VIEW des AS
      SELECT 0 as ds, ARRAY [%d]::int[] as ac union all
      SELECT * FROM find_degree(1, 6, ARRAY [%d]::INT[], ARRAY [%d]::INT[]);

    CREATE OR REPLACE VIEW movies_actors AS
      SELECT act.movie_id, array_agg(act.actor_id) as actors
      FROM acting act GROUP BY act.movie_id;
        
    
    CREATE OR REPLACE FUNCTION find_all_actors(d int, to_value int[])
      RETURNS TABLE (_from int, _to int) AS $$
    
        DECLARE
          _to int[];
          old_actors int[];
        BEGIN
    
          SELECT array_agg(act.actor_id), array_agg(main_id) into _to, old_actors 
          FROM acting act JOIN (select unnest(to_value)  as main_id) main_ac
          ON exists (SELECT movie_id FROM acting WHERE actor_id in (main_ac.main_id) AND act.movie_id = acting.movie_id)
          AND (act.actor_id in (SELECT unnest(ac)::int FROM des WHERE ds = d - 1));
    
          RETURN QUERY SELECT unnest(_to), unnest(old_actors);
    
          IF d - 1 > 0 THEN
            RETURN QUERY SELECT * FROM find_all_actors(d - 1, _to::int[]);
          END IF ;
    
        END ;
    
    $$ LANGUAGE plpgsql;
    
    CREATE OR REPLACE VIEW new_test AS
        SELECT * FROM find_all_actors((select ds from des where (%d = any(ac))), array [%d]::int[]);
        

QUERY;

dbQuery($db, mkSQL($query, $actor1[0], $actor1[0], $actor1[0],$actor2[0], $actor2[0]));

$query = <<<GET
    WITH RECURSIVE shortest(_from,_to,vv) AS (
      -- initial set
      SELECT _from, _to,  ARRAY [_from, _to] FROM new_test
        WHERE _from= %d
    UNION ALL
      SELECT s._from,tm._to,vv||tm._to
        FROM shortest s, new_test tm
        WHERE s._to=tm._from
          AND NOT (tm._to = any(vv))
    ) SELECT distinct(vv) FROM shortest
        WHERE _to = %d;
GET;

$result = [];
$final = [];
$temp = [];
$last = [];


// $res = dbQuery($db, mkSQL($query, $actor1[0],$actor2[0]));

$all_actors = dbQuery($db, mkSQL($query, $actor1[0],$actor2[0]));
$num = 1;
while ($res = dbNext($all_actors)) {
     // print_r($res);
    $str = str_replace('{','',$res[0]);
    $str = str_replace('}','',$str);
    $res = explode(',', $str);
    $final = show_res($db, $res, $result, $final, $temp);
}

if (count($final) > 1) {
    for ($i = 0; $i < count($final); $i ++) {
        array_push($last, join("; ", $final[$i]));
    }
} else {
    $last = $final[0];
}

if ($last == null) {
    return;
}

sort($last);
for ($i = 0; $i < count($last); $i ++) {
    echo "$num. ";
    print($last[$i]);
    echo "\n";
    $num ++;
}


function show_res($db,$res, $result, $final, $temp) {

    for ($i = 0; $i < count($res) - 1; $i ++) {
        // echo "$res[$i] ".$res[$i+1]."\n";
        $temp_search = search_res($db, $res[$i], $res[$i+1]);
        if (count($temp_search) != 0)
            array_push($result, $temp_search);
        // print_r($result);
    }

    if (count($result) == 1) {
        return $result;
    }

    return enumerate($result,$temp,$final);
}

function enumerate($input, $current, $result, $index = 0) {

    if (count($current) == count($input)) {
        array_push($result, $current);
    } else {
        for ($i = 0; $i < count($input[$index]); $i ++) {
            array_push($current, $input[$index][$i]);
            $result = enumerate($input, $current, $result, $index + 1);
            array_pop($current);
        }
    }
    return $result;
}

function search_res($db,$a1, $a2) {

    $query = <<<SEARCH
    SELECT movie_id from movies_actors where  (%d = any(actors)) and (%d = any(actors))
SEARCH;
    $res = dbQuery($db, mkSQL($query, $a1, $a2));
    $merge = [];

    while ($tuple = dbNext($res)) {
        $get_title = <<<TITLE
        select title, year from movie where id = %d
TITLE;
        $movie = dbNext(dbQuery($db, mkSQL($get_title, $tuple[0])));
        array_push($merge, get_actor_name($db,$a1)." was in $movie[0] ($movie[1]) with ".get_actor_name($db, $a2));

    }
    // print_r($merge);
    return $merge;

}


function get_actor_name($db, $ac) {
    $query = <<<SEARCH
    SELECT name from actor where id = %d
SEARCH;
    $res = dbNext(dbQuery($db, mkSQL($query, $ac)));

    return $res[0];
}

$query = <<<DROPSTUFF
    DROP INDEX ac;
    DROP INDEX a;
    DROP FUNCTION find_degree(start_value INTEGER, end_value INTEGER, start_actors INT[], all_actors INT[]) CASCADE;
    DROP FUNCTION find_all_actors(d int, to_value int[]) CASCADE ;

DROPSTUFF;

dbQuery($db, mkSQL($query));

?>
