#!/usr/bin/php
<?php

require("a2.php");

// PROGRAM BODY BEGINS

$usage = "Usage: $argv[0] K StartYear EndYear\nUsage: $argv[0] Genres K StartYear EndYear";
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 4 or count($argv) > 5) exit("$usage\n");

// firstly, we need get the actor
if (count($argv) == 4) {
    if ($argv[1] < 1 or $argv[1] > 1000) exit("$usage\n");
    if ($argv[2] > $argv[3] or $argv[2] < 1900 or $argv[3] >= 2020) exit("$usage\n");

    three_args($db, $argv[2], $argv[3], $argv[1]);
} elseif (count($argv) == 5) {
    if ($argv[2] < 1 or $argv[2] > 1000) exit("$usage\n");
    if ($argv[3] > $argv[4] or $argv[3] < 1900 or $argv[4] >= 2020) exit("$usage\n");

    $all_genres = $argv[1];
    $limit = $argv[2];
    $start = $argv[3];
    $end = $argv[4];
    // we need the string like: %Action%Sci-Fi"
    // because my sql merge all of them together with order like: Action, Sci-Fi
    $genre = "%";
    // it's gonna do something for genre
    $genres = explode("&", $all_genres);
    // for case insensitive
    $genres = make_case($genres);
    // beacause i merge all the genre with ASC order
    // so i need to sort here also
    sort($genres);
    $genre .= join("%", $genres);
    $genre .= "%";

    four_args($db, $genre,$start,$end,$limit);
}


/**
 * @param $genres is an array which contain strings
 * @return $genres which all string become lower
 */
function make_case ($genres) {
    for ($i = 0; $i < count($genres); $i ++) {
        $genres[$i] = strtolower($genres[$i]);
    }

    return $genres;
}


/**
 * @param $db database
 * @param $start start year
 * @param $end end year
 * @param $limit limit number
 *
 * this is for three args function
 */
function three_args ($db, $start, $end, $limit) {

    make_view($db, $start, $end);
    $query = <<<QUE
    SELECT * FROM task3 limit %d
QUE;

    $res = dbQuery($db,mkSQL($query, $limit));
    show_res($res);
}


function four_args ($db, $genre, $start, $end, $limit) {
    make_view($db, $start, $end);

    $query = <<<QUE
    select * from task3 where lower(genre) like %s  limit %d; 
QUE;

    $res = dbQuery($db, mkSQL($query, $genre, $limit));
    show_res($res);
}

// just create a help view
function make_view($db, $start, $end) {

    $view = <<<MAKEVIEW
    CREATE OR REPLACE VIEW task3 AS
    SELECT m.title, m.year, m.content_rating, m.lang, ra.imdb_score, 
           string_agg(g.genre,',' order by g.genre ASC ) as genre, ra.num_voted_users
    FROM movie m LEFT OUTER JOIN rating ra ON m.id = ra.movie_id LEFT OUTER JOIN genre g ON m.id = g.movie_id
    WHERE EXISTS (
        SELECT mo.id FROM movie mo WHERE mo.year >= %d AND mo.year <= %d AND m.id = mo.id
    ) GROUP BY m.title, m.year, m.content_rating, ra.imdb_score, ra.num_voted_users, m.lang
    ORDER BY imdb_score DESC, num_voted_users DESC ;
MAKEVIEW;

    dbQuery($db, mkSQL($view, $start, $end));
}

// drop what i create in this task
function drop_view($db) {
    $query = "DROP VIEW task3";
    dbQuery($db, mkSQL($query));
}


/**
 * @param $res reslut
 */
function show_res($res) {
    $index = 1;
    while ($tuple = dbNext($res)) {

        echo "$index. $tuple[0] (";
        if (!empty($tuple[1])) {
            echo  "$tuple[1], ";
        }

        if (!empty($tuple[2])) {
            echo  "$tuple[2], ";
        }

        if (!empty($tuple[3])) {
            echo "$tuple[3]";
        }
        echo ")";
        echo " [";
        if (!empty($tuple[4])) {
            echo "$tuple[4], ";
        }
        if (!empty($tuple[6])) {
            echo "$tuple[6]";
        }

        echo "]\n";
        $index ++;
    }
}

// after finish that, then drop it
drop_view($db);

?>
